<?php

namespace Database\Seeders;

use App\Models\Noo;
use Illuminate\Database\Seeder;

class NooSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Noo::insert([
            [
            'user_id' => 1,
            'nama_outlet' => 'NOO 1',
            'alamat_outlet' => 'JL. NOO 1',
            'nama_pemilik_outlet' => 'Pemilik Noo 1',
            'nomer_tlp_outlet' => '089660111111',
            'nomer_wakil_outlet' => '089660111112',
            'ktp_outlet' => '1111111111111111',
            'kota' => 'Kota 1',
            'region' => 'WJU',
            'cluster_id' => 1,
            'poto_shop_sign' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
            'poto_etalase' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
            'poto_depan' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
            'poto_belakang' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
            'poto_kiri' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
            'poto_kanan' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
            'video' => "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
            'created_at' => '2021-08-24',
            'oppo' => "2",
            'vivo' => "2",
            'realme' => "1",
            'samsung' => "2",
            'xiaomi' => "1",
            'fl' => "3",
            'status' => 'PENDING',
            'confirmed_at' => null,
            'confirmed_by' => null,
            'limit' => null,
            'approved_at' => null,
            'rejected_at' => null,
            'rejected_by' => null,
            ],
            [
                'user_id' => 1,
                'nama_outlet' => 'NOO 2',
                'alamat_outlet' => 'JL. NOO 2',
                'nama_pemilik_outlet' => 'Pemilik Noo 2',
                'nomer_tlp_outlet' => '089660222222',
                'nomer_wakil_outlet' => '089660222222',
                'ktp_outlet' => '2222222222222222',
                'kota' => 'Kota 2',
                'region' => 'WJU',
                'cluster_id' => 1,
                'poto_shop_sign' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
                'poto_etalase' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
                'poto_depan' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
                'poto_belakang' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
                'poto_kiri' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
                'poto_kanan' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
                'video' => "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
                'created_at' => '2021-08-24',
                'oppo' => "1",
                'vivo' => "1",
                'realme' => "1",
                'samsung' => "2",
                'xiaomi' => "1",
                'fl' => "2",
                'status' => 'CONFIRMED',
                'confirmed_at' => '2021-08-24',
                'confirmed_by' => 'AR2',
                'limit' => 10000000,
                'approved_at' => null,
                'rejected_at' => null,
                'rejected_by' => null,
            ],
            [
                'user_id' => 1,
                'nama_outlet' => 'NOO 3',
                'alamat_outlet' => 'JL. NOO 3',
                'nama_pemilik_outlet' => 'Pemilik Noo 3',
                'nomer_tlp_outlet' => '089660333333',
                'nomer_wakil_outlet' => '089660333333',
                'ktp_outlet' => '3333333333333333',
                'kota' => 'Kota 3',
                'region' => 'WJU',
                'cluster_id' => 1,
                'poto_shop_sign' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
                'poto_etalase' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
                'poto_depan' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
                'poto_belakang' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
                'poto_kiri' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
                'poto_kanan' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
                'video' => "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
                'created_at' => '2021-08-24',
                'oppo' => "2",
                'vivo' => "2",
                'realme' => "1",
                'samsung' => "2",
                'xiaomi' => "1",
                'fl' => "3",
                'status' => 'APPROVED',
                'confirmed_at' => '2021-08-24',
                'confirmed_by' => 'AR3',
                'limit' => 25000000,
                'approved_at' => '2021-08-24',
                'rejected_at' => null,
                'rejected_by' => null,
            ],
            [
                'user_id' => 1,
                'nama_outlet' => 'NOO 4',
                'alamat_outlet' => 'JL. NOO 4',
                'nama_pemilik_outlet' => 'Pemilik Noo 4',
                'nomer_tlp_outlet' => '089660444444',
                'nomer_wakil_outlet' => '089660444444',
                'ktp_outlet' => '4444444444444444',
                'kota' => 'Kota 4',
                'region' => 'WJU',
                'cluster_id' => 1,
                'poto_shop_sign' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
                'poto_etalase' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
                'poto_depan' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
                'poto_belakang' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
                'poto_kiri' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
                'poto_kanan' => "https://i.im.ge/2021/07/28/IDr9C.jpg",
                'video' => "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
                'created_at' => '2021-08-24',
                'oppo' => "2",
                'vivo' => "2",
                'realme' => "1",
                'samsung' => "2",
                'xiaomi' => "1",
                'fl' => "3",
                'status' => 'APPROVED',
                'confirmed_at' => '2021-08-24',
                'confirmed_by' => 'AR4',
                'limit' => 25000000,
                'approved_at' => '2021-08-24',
                'rejected_at' => '2021-08-24',
                'rejected_by' => 'JEJEN',
            ],
        ]);
    }
}
