<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        User::insert([
            [
                'username' => 'tmswj',
                'nama_lengkap' => 'TMSWJ',
                'badanusaha_id' => 1,
                'divisi_id' => 6,
                'role_id' => 1,
                'region_id' => 1,
                'cluster_id' => 32,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'tmnwj',
                'nama_lengkap' => 'TMNWJ',
                'badanusaha_id' => 1,
                'divisi_id' => 6,
                'role_id' => 1,
                'region_id' => 2,
                'cluster_id' => 32,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'tmscj',
                'nama_lengkap' => 'TMSCJ',
                'badanusaha_id' => 1,
                'divisi_id' => 6,
                'role_id' => 1,
                'region_id' => 3,
                'cluster_id' => 32,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'tmncj',
                'nama_lengkap' => 'TMNCJ',
                'badanusaha_id' => 1,
                'divisi_id' => 6,
                'role_id' => 1,
                'region_id' => 4,
                'cluster_id' => 32,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'tmsej',
                'nama_lengkap' => 'TMSEJ',
                'badanusaha_id' => 1,
                'divisi_id' => 6,
                'role_id' => 1,
                'region_id' => 5,
                'cluster_id' => 32,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'tmnej',
                'nama_lengkap' => 'TMSNEJ',
                'badanusaha_id' => 1,
                'divisi_id' => 6,
                'role_id' => 1,
                'region_id' => 6,
                'cluster_id' => 32,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'tmjabo',
                'nama_lengkap' => 'TMJABO',
                'badanusaha_id' => 1,
                'divisi_id' => 6,
                'role_id' => 1,
                'region_id' => 7,
                'cluster_id' => 32,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'ascswj',
                'nama_lengkap' => 'ASCSWJ',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 2,
                'region_id' => 1,
                'cluster_id' => 32,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'ascnwj',
                'nama_lengkap' => 'ASCNWJ',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 2,
                'region_id' => 2,
                'cluster_id' => 32,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'ascscj',
                'nama_lengkap' => 'ASCSCJ',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 2,
                'region_id' => 3,
                'cluster_id' => 32,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'ascncj',
                'nama_lengkap' => 'ASCNCJ',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 2,
                'region_id' => 4,
                'cluster_id' => 32,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'ascsej',
                'nama_lengkap' => 'ASCSEJ',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 2,
                'region_id' => 5,
                'cluster_id' => 32,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'ascnej',
                'nama_lengkap' => 'ASCNEJ',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 2,
                'region_id' => 6,
                'cluster_id' => 32,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'ascjabo',
                'nama_lengkap' => 'ASCJABO',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 2,
                'region_id' => 7,
                'cluster_id' => 32,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfcw1',
                'nama_lengkap' => 'DSFCW1',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 1,
                'cluster_id' => 1,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfcw2',
                'nama_lengkap' => 'DSFCW2',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 1,
                'cluster_id' => 2,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfcw3',
                'nama_lengkap' => 'DSFCW3',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 1,
                'cluster_id' => 3,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfcw4',
                'nama_lengkap' => 'DSFCW4',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 1,
                'cluster_id' => 4,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfcw5',
                'nama_lengkap' => 'DSFCW5',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 1,
                'cluster_id' => 5,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfcw6',
                'nama_lengkap' => 'DSFCW6',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 1,
                'cluster_id' => 6,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfcw7',
                'nama_lengkap' => 'DSFCW7',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 2,
                'cluster_id' => 7,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfcw8',
                'nama_lengkap' => 'DSFCW8',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 2,
                'cluster_id' => 8,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfcw9',
                'nama_lengkap' => 'DSFCW9',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 2,
                'cluster_id' => 9,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfcw10',
                'nama_lengkap' => 'DSFCW10',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 2,
                'cluster_id' => 10,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfcj1',
                'nama_lengkap' => 'DSFCJ1',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 4,
                'cluster_id' => 11,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfcj2',
                'nama_lengkap' => 'DSFCJ2',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 4,
                'cluster_id' => 12,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfcj3',
                'nama_lengkap' => 'DSFCJ3',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 4,
                'cluster_id' => 13,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfcj4',
                'nama_lengkap' => 'DSFCJ4',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 4,
                'cluster_id' => 14,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfcj5',
                'nama_lengkap' => 'DSFCJ5',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 4,
                'cluster_id' => 15,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfcj6',
                'nama_lengkap' => 'DSFCJ6',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 3,
                'cluster_id' => 16,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfcj7',
                'nama_lengkap' => 'DSFCJ7',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 3,
                'cluster_id' => 17,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfcj8',
                'nama_lengkap' => 'DSFCJ8',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 3,
                'cluster_id' => 18,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfcj9',
                'nama_lengkap' => 'DSFCJ9',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 3,
                'cluster_id' => 19,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfcj10',
                'nama_lengkap' => 'DSFCJ10',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 3,
                'cluster_id' => 20,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfej1',
                'nama_lengkap' => 'DSFEJ1',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 5,
                'cluster_id' => 21,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfej2',
                'nama_lengkap' => 'DSFEJ2',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 5,
                'cluster_id' => 22,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfej3',
                'nama_lengkap' => 'DSFEJ3',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 5,
                'cluster_id' => 23,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfej4',
                'nama_lengkap' => 'DSFEJ4',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 5,
                'cluster_id' => 24,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfej5',
                'nama_lengkap' => 'DSFEJ5',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 5,
                'cluster_id' => 25,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfej6',
                'nama_lengkap' => 'DSFEJ6',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 6,
                'cluster_id' => 26,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfej7',
                'nama_lengkap' => 'DSFEJ7',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 6,
                'cluster_id' => 27,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfej8',
                'nama_lengkap' => 'DSFEJ8',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 6,
                'cluster_id' => 28,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfej9',
                'nama_lengkap' => 'DSFEJ9',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 6,
                'cluster_id' => 29,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfej10',
                'nama_lengkap' => 'DSFEJ10',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 6,
                'cluster_id' => 30,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'dsfjabo1',
                'nama_lengkap' => 'DSFJABO1',
                'badanusaha_id' => 1,
                'divisi_id' => 1,
                'role_id' => 3,
                'region_id' => 7,
                'cluster_id' => 31,
                'password' => bcrypt('complete123'),
            ],
            [
                'username' => 'admin',
                'nama_lengkap' => 'NAMA ADMIN',
                'region_id' => 8,
                'divisi_id' => 5,
                'badanusaha_id' => 3,
                'cluster_id' => 32,
                'role_id' => 5,
                'password' => bcrypt('complete123'),
            ],
        ]);
    }
}
